import {StyleSheet} from 'react-native';
import {scale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: scale(660),
    width: scale(350),
    backgroundColor: '#f0f0f0',
  },
  image: {
    flex: 1,
    height: scale(180),
    width: scale(350),
  },
  imageCourseContainer: {
    width: scale(130),
    height: scale(110),
    alignItems: 'center',
  },
  imageLess: {
    flex: 1,
    height: scale(80),
    width: scale(115),
    overflow: 'hidden',
    borderRadius: scale(10),
  },
  image23: {
    flex: 1,
    height: scale(160),
    width: scale(330),
  },
  logocontainer: {
    height: scale(200),
    width: scale(350),
    justifyContent: 'center',
    alignItems: 'center',
  },
  textInputContainer: {
    height: scale(160),
    width: scale(350),
    alignItems: 'center',
    marginTop: scale(50),
  },
  textContainer: {
    height: scale(260),
    width: scale(320),
    alignSelf: 'center',
  },
  textTitile: {
    fontSize: scale(20),
  },
  text: {
    fontSize: scale(14),
    marginLeft: scale(5),
  },
  scrollArea: {
    flex: 1,
  },
  dataContainer: {
    flex: 1,
  },
  item: {
    padding: scale(5),
    marginVertical: scale(5),
    marginHorizontal: scale(8),
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: scale(15),
    elevation: scale(5),
  },
  detailcourse: {
    width: scale(190),
    height: scale(110),
  },
  title: {
    fontSize: 17,
    marginLeft: scale(5),
    flexWrap: 'wrap',
    fontWeight: 'bold',
  },
  iconAndText: {
    marginLeft: scale(5),
    flexDirection: 'row',
    alignItems: 'center',
  },
  bar: {
    height: scale(5),
    width: scale(143),
    backgroundColor: '#e0e0e0',
    borderRadius: scale(5 / 2),
  },
  processbar: {
    height: scale(5),
    width: scale(100),
    backgroundColor: 'orange',
    borderRadius: scale(5 / 2),
  },
  itemTest: {
    marginHorizontal: scale(8),
    alignItems: 'center',
    borderRadius: scale(15),
    marginVertical: scale(8),
    borderRightColor: '#d3d4d4',
    height: scale(200),
    elevation: scale(5),
  },
  viewTest: {
    height: scale(70),
    width: scale(145),
  },
  titleTest: {
    fontSize: scale(14),
    marginLeft: scale(5),
    fontWeight: 'bold',
  },
  textTest: {
    fontSize: scale(10),
    marginLeft: scale(5),
  },
  imageTest: {
    flex: 1,
    height: scale(90),
    width: scale(159),
    overflow: 'hidden',
    borderTopLeftRadius: scale(15),
    borderTopRightRadius: scale(15),
  },
  searchBar: {
    height: scale(60),
    width: scale(350),
    backgroundColor: '#3b7ad0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconPosition: {
    marginLeft: scale(8),
    marginRight: scale(8),
  },
  searchInput: {
    backgroundColor: 'white',
    height: scale(40),
    width: scale(235),
    borderRadius: scale(20),
    flexDirection: 'row',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'orange',
    width: scale(290),
    height: scale(50),
    alignSelf: 'center',
    borderRadius: scale(25),
    marginBottom: scale(20),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: scale(20),
  },
  buttonText: {
    fontSize: scale(20),
    color: 'white',
  },
  topTittle: {
    fontSize: scale(18),
    marginLeft: scale(40),
    color: 'white',
  },
  topTittle1: {
    fontSize: scale(18),
    marginLeft: scale(40),
    color: 'white',
  },
  tabBar: {
    height: scale(50),
    width: scale(350),
    flexDirection: 'row',
  },
  tabBarButton: {
    height: scale(50),
    width: scale(116),
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceContainer: {
    marginTop: '30%',
    height: scale(400),
    width: scale(350),
    alignItems: 'center',
  },
  choice: {
    marginTop: scale(30),
    height: scale(30),
    width: scale(200),
    flexDirection: 'row',
    alignItems: 'center',
  },
  textchoice: {
    fontSize: scale(14),
    marginLeft: scale(5),
  },
  circle: {
    height: scale(20),
    width: scale(20),
    borderRadius: scale(10),
    backgroundColor: '#3b7ad0',
    justifyContent: 'center',
  },
  circleTouch: {
    height: scale(16),
    width: scale(16),
    borderRadius: scale(8),
    alignSelf: 'center',
  },
  codeInput: {
    backgroundColor: 'white',
    width: scale(290),
    height: scale(50),
    alignSelf: 'center',
    borderRadius: scale(25),
    marginTop: scale(20),
    alignContent: 'center',
    justifyContent: 'center',
  },
  codeText: {
    fontSize: scale(18),
    color: 'black',
    alignSelf: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  topView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal2View: {
    height: scale(120),
    width: scale(300),
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    elevation: 5,
  },
  modalView: {
    height: scale(300),
    width: scale(300),
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    elevation: 5,
  },
  openButton: {
    alignSelf: 'auto',
    width: scale(50),
    borderRadius: scale(10),
    padding: 10,
    elevation: 2,
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: scale(18),
  },
  modalText: {
    fontSize: scale(16),
    marginTop: scale(15),
    marginBottom: scale(15),
  },
  modal2Text: {
    marginTop: scale(5),
    marginBottom: scale(5),
    textAlign: 'center',
    fontSize: scale(16),
  },
  modalBottomView: {
    height: '60%',
    width: '100%',
    backgroundColor: 'white',
  },
  bottomView: {
    backgroundColor: 'rgba(100,100,100, 0.5)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: scale(30),
    marginRight: scale(100),
    justifyContent: 'space-between',
  },
  listdropdown: {
    marginLeft: scale(50),
  },
  dropdowntext: {
    fontSize: scale(14),
    marginBottom: scale(5),
  },
  hideButton: {
    marginTop: scale(100),
    marginLeft: scale(280),
    justifyContent: 'center',
    width: scale(60),
    height: scale(60),
    borderRadius: scale(30),
    padding: 10,
    backgroundColor: 'rgba(100,100,100, 0.5)',
  },
});

export default styles;
